version: '3.3'
services:
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    privileged: true
    ports:
      - 80:80
    volumes:
      - D:\wsl\docker-desktop-data\nginx\conf\nginx.conf:/etc/nginx/nginx.conf:ro
      - D:\wsl\docker-desktop-data\nginx\www:/usr/share/nginx/html
      - D:\wsl\docker-desktop-data\nginx\logs:/var/log/nginx
