version: "3"
services:
  ide_vscode_all_in_one:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-allinone-v2-vscode:latest
    hostname: dev-container
    restart: always
    environment:
      LOCAL_USER_PASSWORD: root123
    volumes:
      - .:/home/project
    ports:
      - "6822:22"
      - "6800:3000"
      - "8000:8000"
    networks:
      - smartide-network

networks:
  smartide-network:
    external: true
