version: "3"

services:
  mysql8.0:
    # 镜像名
    image: mysql:8.0.32
    # 容器名(以后的控制都通过这个)
    container_name: mysql8.0
    # 重启策略
    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root 密码
      MYSQL_ROOT_PASSWORD: root
      # 初始化数据库(后续的初始化sql会在这个库执行)
      MYSQL_DATABASE: test
      # 初始化用户(不能是root 会报错, 后续需要给新用户赋予权限)
      MYSQL_USER: quanzaiyu
      # 用户密码
      MYSQL_PASSWORD: 123456
    # 映射端口
    ports:
      - 3306:3306
    volumes:
      # 挂载初始化目录
      - D:\wsl\docker-desktop-data\8.0\mysql\db:/docker-entrypoint-initdb.d
      # 挂载配置
      - D:\wsl\docker-desktop-data\8.0\mysql\conf:/etc/mysql/conf.d
      # 挂载日志
      - D:\wsl\docker-desktop-data\8.0\mysql\logs:/logs
      # 挂载数据
      - D:\wsl\docker-desktop-data\8.0\mysql\data:/var/lib/mysql
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
