version: "3.3"

services:
  webapp:
    image: "node:latest"
    user: "root"
    working_dir: "/home/app"
    ports: [ 4000:4000 ]
    volumes:
      - D:\wsl\docker-desktop-data\node.js\app:/home/app
    command:
      - /bin/sh
      - -c
      - |
        npm -v
        npm config set registry https://registry.npm.taobao.org
        cd /home/app
        npm install
        npm run dev
        tail -f /dev/null
    tty: true
    stdin_open: true
